src/Entity/Xseance.php
<?php

namespace App\Entity;

use App\Repository\XseanceRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: XseanceRepository::class)]
class Xseance
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Feuillea;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $ID_Séance;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Typeséance;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Etablissement;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Formation;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Promotion;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Année;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Année_Lib;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Semestre;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Groupe;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Module;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Element;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Enseignant;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $ID_Salle;

    #[ORM\Column(type: 'date', nullable: true)]
    private $Date_Séance;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $semaine;

    #[ORM\Column(type: 'time', nullable: true)]
    private $Heure_Debut;

    #[ORM\Column(type: 'time', nullable: true)]
    private $Heure_Fin;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $Traitement;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $Cloturer;

    #[ORM\Column(type: 'date', nullable: true)]
    private $Date_Sys;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $Statut;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $Existe;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $Signé;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $Annulée;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIDFeuilleA(): ?string
    {
        return $this->ID_Feuillea;
    }

    public function setIDFeuilleA(?string $ID_Feuillea): self
    {
        $this->ID_Feuillea = $ID_Feuillea;

        return $this;
    }

    public function getIDSéance(): ?int
    {
        return $this->ID_Séance;
    }

    public function setIDSéance(?int $ID_Séance): self
    {
        $this->ID_Séance = $ID_Séance;

        return $this;
    }

    public function getTypeséance(): ?string
    {
        return $this->Typeséance;
    }

    public function setTypeséance(?string $Typeséance): self
    {
        $this->Typeséance = $Typeséance;

        return $this;
    }

    public function getIDEtablissement(): ?string
    {
        return $this->ID_Etablissement;
    }

    public function setIDEtablissement(?string $ID_Etablissement): self
    {
        $this->ID_Etablissement = $ID_Etablissement;

        return $this;
    }

    public function getIDFormation(): ?string
    {
        return $this->ID_Formation;
    }

    public function setIDFormation(?string $ID_Formation): self
    {
        $this->ID_Formation = $ID_Formation;

        return $this;
    }

    public function getIDPromotion(): ?string
    {
        return $this->ID_Promotion;
    }

    public function setIDPromotion(?string $ID_Promotion): self
    {
        $this->ID_Promotion = $ID_Promotion;

        return $this;
    }

    public function getIDAnnée(): ?string
    {
        return $this->ID_Année;
    }

    public function setIDAnnée(?string $ID_Année): self
    {
        $this->ID_Année = $ID_Année;

        return $this;
    }

    public function getAnnéeLib(): ?string
    {
        return $this->Année_Lib;
    }

    public function setAnnéeLib(?string $Année_Lib): self
    {
        $this->Année_Lib = $Année_Lib;

        return $this;
    }

    public function getIDSemestre(): ?string
    {
        return $this->ID_Semestre;
    }

    public function setIDSemestre(?string $ID_Semestre): self
    {
        $this->ID_Semestre = $ID_Semestre;

        return $this;
    }

    public function getGroupe(): ?string
    {
        return $this->Groupe;
    }

    public function setGroupe(?string $Groupe): self
    {
        $this->Groupe = $Groupe;

        return $this;
    }

    public function getIDModule(): ?string
    {
        return $this->ID_Module;
    }

    public function setIDModule(?string $ID_Module): self
    {
        $this->ID_Module = $ID_Module;

        return $this;
    }

    public function getIDElement(): ?string
    {
        return $this->ID_Element;
    }

    public function setIDElement(?string $ID_Element): self
    {
        $this->ID_Element = $ID_Element;

        return $this;
    }

    public function getIDEnseignant(): ?string
    {
        return $this->ID_Enseignant;
    }

    public function setIDEnseignant(?string $ID_Enseignant): self
    {
        $this->ID_Enseignant = $ID_Enseignant;

        return $this;
    }

    public function getIDSalle(): ?string
    {
        return $this->ID_Salle;
    }

    public function setIDSalle(?string $ID_Salle): self
    {
        $this->ID_Salle = $ID_Salle;

        return $this;
    }

    public function getDateSéance(): ?\DateTimeInterface
    {
        return $this->Date_Séance;
    }

    public function setDateSéance(?\DateTimeInterface $Date_Séance): self
    {
        $this->Date_Séance = $Date_Séance;

        return $this;
    }

    public function getSemaine(): ?int
    {
        return $this->semaine;
    }

    public function setSemaine(?int $semaine): self
    {
        $this->semaine = $semaine;

        return $this;
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->Heure_Debut;
    }

    public function setHeureDebut(?\DateTimeInterface $Heure_Debut): self
    {
        $this->Heure_Debut = $Heure_Debut;

        return $this;
    }

    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->Heure_Fin;
    }

    public function setHeureFin(?\DateTimeInterface $Heure_Fin): self
    {
        $this->Heure_Fin = $Heure_Fin;

        return $this;
    }

    public function getTraitement(): ?int
    {
        return $this->Traitement;
    }

    public function setTraitement(?int $Traitement): self
    {
        $this->Traitement = $Traitement;

        return $this;
    }

    public function getCloturer(): ?int
    {
        return $this->Cloturer;
    }

    public function setCloturer(?int $Cloturer): self
    {
        $this->Cloturer = $Cloturer;

        return $this;
    }

    public function getDateSys(): ?\DateTimeInterface
    {
        return $this->Date_Sys;
    }

    public function setDateSys(?\DateTimeInterface $Date_Sys): self
    {
        $this->Date_Sys = $Date_Sys;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->Statut;
    }

    public function setStatut(?int $Statut): self
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getExiste(): ?int
    {
        return $this->Existe;
    }

    public function setExiste(?int $Existe): self
    {
        $this->Existe = $Existe;

        return $this;
    }

    public function getSigné(): ?int
    {
        return $this->Signé;
    }

    public function setSigné(?int $Signé): self
    {
        $this->Signé = $Signé;

        return $this;
    }

    public function getAnnulée(): ?int
    {
        return $this->Annulée;
    }

    public function setAnnulée(?int $Annulée): self
    {
        $this->Annulée = $Annulée;

        return $this;
    }
}

templates/traitement/pdfs/feuilleAppel.html.twig
<!DOCTYPE html>
<html>
<head>
<style>
.column {
  float: left;
  padding: 10px;
}

.left {
  width: 65%;
}

.right {
  width: 25%;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
body { margin-top: 0px;margin-bottom: 0px;
font-size:12px;
 }
 #customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
 


}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 5px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
    font-size:10px;
 
  text-align: left;
  background-color: lightblue;
  color: black;
  
}

       .page-number:before {
  content: "Page " counter(page);
}
</style>
</head>
{% set page = 0 %}

<body>

<div>
<table class="table" width="100%"  id="customers">
    <thead>
      <tr>
        <th >N°</th>
        <th >ID ETUDIANT</th>
        <th>NOM</th>        
        <th>PRENOM</th>
        <th>HEURE POIN</th>  
        <th style="text-align:center;">OBSERVATION</th>
        <th style="text-align:center;">Categorie Ens</th>



        

      </tr>
      
      </thead>
      <tbody>
    <tr  style="background:lightgreen; text-align:center !important;letter-spacing:1.5px;">
    <td align="center" colspan=7>Categories: A</td>
    </tr>
      {% set count = 0 %}
    {% for et in etudiantA %}
    {% set count = count + 1 %}
   
      <tr>
      <td >{{ count }}</td>
        <td >{{et.id_admission}} </td>
        <td>{{et.Nom}} </td>
        <td>{{et.Prénom}}</td>
          <td>{{et.Heure_Pointage}}</td>
        <td style="text-align:center;">{{et.Categorie}}</td>
         <td></td>
      </tr> 
       
    
{% endfor %}

 <tr style="background:#FFFACD; text-align:center;letter-spacing:1.5px;">
    <td align="center"  colspan=7>Categories: B</td>
    </tr>
    {% for B in etudiantB %}
    {% set count = count + 1 %}
      <tr>
      <td>{{ count }}</td>
        <td >{{B.id_admission}} </td>
        <td>{{B.Nom}} </td>
        <td>{{B.Prénom}}</td>
          <td>{{B.Heure_Pointage}}</td>
        <td style="text-align:center;">{{B.Categorie}}</td>
        <td></td>
        
      </tr> 
       
    
{% endfor %}
<tr style="background:#FFA500; text-align:center;letter-spacing:1.5px;">
    <td align="center"  colspan=7>Categories: C</td>
    </tr>
    {% for C in etudiantC %}
    {% set count = count + 1 %}
      <tr>
      <td>{{ count }}</td>
        <td >{{C.id_admission}} </td>
        <td>{{C.Nom}} </td>
        <td>{{C.Prénom}}</td>
          <td>{{C.Heure_Pointage}}</td>
        <td style="text-align:center;">{{C.Categorie}}</td>
         <td></td>
      </tr> 
       
    
{% endfor %}
<tr style="background:#FF4500; text-align:center;letter-spacing:1.5px;">
    <td align="center"  colspan=7>Categories: D</td>
    </tr>
    {% for D in etudiantD %}
    {% set count = count + 1 %}
      <tr>
      <td>{{ count }}</td>
        <td >{{D.id_admission}} </td>
        <td>{{D.Nom}} </td>
        <td>{{D.Prénom}}</td>
          <td>{{D.Heure_Pointage}}</td>
        <td style="text-align:center;">{{D.Categorie}}</td>
         <td></td>
      </tr> 
       
    
{% endfor %}
    </tbody>
      </table>
      </div>
   
</body>
</html>

templates/traitement/pdfs/footer.html.twig
 

 <div class="page-number"></div>
           <p>{{ date }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Année Universitaire: {{emptime.programmation.annee.designation}}</p>

templates/traitement/pdfs/header.html.twig
<style>

</style>
<image src="{{ asset('assets/img/logo/Logo_UIASS_bkack2.png') }}" >
<table style="width: 100%;" cellspacing="0">
    <tbody>

        <tr>
            <td style="width:45%; text-align:center"><img style="width:200px;margin: 0 auto;" src="{{ asset('assets/img/logo/Logo_UIASS_bkack2.png') }}" alt="Logo"></td>
            <td style="width:1%;"></td>
            <td style="width:80%;"><h1>FEUILLE D'APPEL </h1></td>
        </tr>
        <tr>
           <td style="width:25%; text-align:center"></td>
            <td style="width:1%;"></td>
            <td  style="width:50%;"><h3>{{ emptime.programmation.element.module.semestre.promotion.formation.etablissement.designation }}</h3></td>
        </tr>
        <tr>
           <td style="width:25%; text-align:center"></td>
            <td style="width:1%;"></td>
            <td  style="width:70%;"><h3>{{ emptime.programmation.element.module.semestre.promotion.formation.designation }}</h3></td>
        </tr>
        <tr>
           <td style="width:25%; text-align:center"></td>
            <td style="width:1%;"></td>
            <td  style="width:80%;"><h3>{{ emptime.programmation.element.module.semestre.promotion.designation }}</ph3></td>
        </tr>
    
    </tbody>

</table>
<br/>
<div class="row">
  <div class="column left" >
  <div style="display: grid; grid-template-columns: 1fr; width: 100%; gap: 10px;" class="grid-container">

  <div style="display: flex; flex-direction: column; border: 1px solid #ccc; padding: 10px;" class="item">
    <div style="margin-bottom: 5px;font-weight: bold; border-bottom: 1px solid #000;">
      ID_Séance / Date: {{emptime.id}} / {{emptime.start |date('Y-m-d')}} /   HD: {{emptime.heurDb | date('H:i')}} HF: {{emptime.heurFin | date('H:i')}}
    </div>
    <div style="margin-bottom: 5px; font-weight:bold; border-bottom: 1px solid #000;">
      MODULE/ELEMENT : 
    </div>
    <div style="margin-bottom: 5px; ">
       {{emptime.programmation.element.module.designation}} - {{emptime.programmation.element.designation}}
    </div>
    <div style="margin-bottom: 5px; font-weight: bold; border-bottom: 1px solid #000;">
      PROFESSEUR : 
    </div>
    <div style="margin-bottom: 5px; ">
      {{emptime.emptimens[0].enseignant.nom}} / {{emptime.emptimens[0].enseignant.prenom}}
    </div>
    <div style="margin-bottom: 5px; font-weight: bold; border-bottom: 1px solid #000;">
      CLASSE/SALLE : 
    </div>
    <div style="margin-bottom: 5px; ">
      {{emptime.salle.designation}} / {% if emptime.groupe %} {{emptime.groupe.niveau}} {% else %} - {% endif %}
    </div>
  </div>

</div>

  </div>
   <div class="column right" >
   
  <div style="font-size:10px;">
A: {{A}}<hr/>
B: {{B}}<hr/>
C: {{C}}<hr/>
D: {{D}}<hr/> 
Total: {{Total}} 

  </div>
  </div>
  </div>